### ISSUE TITLE
一括変換モードの提案

### ISSUE THREAD

**Issue by hibit-at** [discus0434/pdf-translator#3]
便利なアプリありがとうございます。
pdfだとある程度一括して変換したいこともあると思うので、以下のようなオプションはどうでしょうか。

・`-f` というオプションがある場合、`./inputs` フォルダの中にある `*.pdf` を列挙して、それを順々に処理していく
・`make folder-translate` というコマンドで上の形式で python ファイルを読み出す

もし内容に問題がなくて実装にこだわりがなければ、プルリクを送ることも可能です。

**Comment by discus0434** [comment]
提案ありがとうございます！
その機能があると確かに便利ですね。
もしdocstringの追加など、こちらにeditされることについて抵抗がなければプルリク頂けると嬉しいです！
