### ISSUE TITLE
Is reverse translation possible? JA to EN?

### ISSUE THREAD

**Issue by gety9** [discus0434/pdf-translator#5]
Thank you for interesting app, as i understand currently it's doing EN to JA. How easy/difficult it will be to adust the code to achieve reverse translation?

**Comment by discus0434** [comment]
As you see, this app does not perform JA -> EN conversation.
It's easy to make it possible, but apparently OCR models being able to read Japanese sentence in document are not as well as models for English.

If you like, you can substitute these for the models used at [these lines](https://github.com/discus0434/pdf-translator/blob/164ac3946d3fa3494c893233dca6917fa822296b/main.py#L166-L172) in `main.py`:
- [PaddleOCR's JA recognition](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/multi_languages_en.md) 
- [JA -> EN translation](https://huggingface.co/staka/fugumt-ja-en)

**Comment by gety9** [comment]
thank you for quick reply,  could you please also tell:

-, does any NVIDIA GPU will work or is there minimum requirements? currently i don't have GPU (have intel hd graphics 530), so i will need to buy one (to meet project requirements).

-, will i be able to adjust your project to do also Simplified Chinese to English? (as i understand i will just need to find Ch to Eng translation model (instead of staka fugumt), am i right?)

**Comment by discus0434** [comment]
> does any NVIDIA GPU will work or is there minimum requirements? currently i don't have GPU (have intel hd graphics 530), so i will need to buy one (to meet project requirements).

Yes. But you can modify the requirements with not so much difficulty. You need to set up environment with no Dockerfile and delete some `.to("cuda")` from source code. Using AWS' EC2 or something is an alternative way.

> will i be able to adjust your project to do also Simplified Chinese to English? (as i understand i will just need to find Ch to Eng translation model (instead of staka fugumt), am i right?)

Right.

**Comment by gety9** [comment]
@discus0434 thank you for replies, closing

(will open up if have further questions)

**Comment by munish0838** [comment]
> @discus0434 thank you for replies, closing
> 
> (will open up if have further questions)

Hi @gety9, were you able to get the code working without GPU, can you please share the steps
